schedule_interval: "30 * * * *"
tables:
    - click
    - imp
    - info
    - spot
    - state
    - track
    - int
stage_sql_path: adlogs/load_raw_logs
transform_sql_path: adlogs/transform_raw_logs
parent_directory: 'stage_{}_logs_dev'
log_path: 'log/*'


aws_bucket_name: 'das42-airflow-training'

folder: 
    - stage_click_logs_dev
    - stage_imp_logs_dev
    - stage_info_logs_dev
    - stage_spot_logs_dev
    - stage_state_logs_dev
    - stage_track_logs_dev
    - stage_int_logs_dev

data_source: 20190704/15/log #this is the end of the file tree for all files listed in the folder list

aws_conn_id: 'aws_airflow'

#this header check tree below puts parameters for the headercheck function in place globally
header_check:
    filters:
        sanitize_capitalization: False
        trim_whitespace: False
        remove_whitespace: False
        remove_underscores: False
        ignore_columns: []
        delimiter: ","


# The data used in the internal project does not contain header titles so the adaption of this function will 
# not work exactly the same as in the Disney Demo.  The table in this yaml "click_columns" artificially fixed this
# by inputting the first row in each column as header titles so that this header check function passes for the click data
# before it is imported.  For this same reason, the other six pieces of data imported will fail.

# As an additional note, we have disabled the features that sanitize capitalization, trim whitespace, remove whitespace and
# remove underscores as this will also make it fail unless we remove these elements from the yaml list.  if you would like
# to enable these features you will need to be sure your yaml list of columns follows these rules or it
# will obviously fail.
click_columns:
    - Temp
    - '20190704'  
    - '8:10'    
    - '244' 
    - '266' 
    - '1'   
    - '55289-964'   
    - '#8d9b08' 
    - 'com.webmd.Zamit' 
    - g   
    - '234.221.52.176'  
    - '1994'    
    - '2007'    
    - 'Dakota Club' 
    - visa    
    - k13AACCaR   
    - 'America/New_York'    
    - '67-464-6258' 
    - '16563'   
    - rweavers0   
    - 'rweavers0.1' 
    - 'Industrial Machinery/Components' 
    - '833126198'   
    - Sarasota    
    - Florida 
    - 'United States'   
    - 'SedInterdumVenenatis.avi'    
    - '2019070415'  
    - '2019070415.1'


imp_columns:
    - record_type
    - date
    - time
    - idevent_type
    - placementid
    - ipn
    - idcreative
    - config_id
    - GUID
    - geo_db
    - section
    - iab_flag
    - ip_address
    - rule_match
    - keyword
    - custom
    - privacy
    - placement_dt
    - placement_path
    - creative_dt
    - creative_path
    - domain
    - parent_time
    - device_id
    - imp_id
    - agent_env
    - user_agent
    - impression_guid
    - unhex_md5_smartclip
    - idcampaign
    - c2
    - c3
    - file_source
    - load_timestamp
    - run_datehour

info_columns:
    -record_type 
    -date
    -time
    -error_severity
    -error_number
    -placement_id
    -error_message
    -ip_address
    -referrer
    -iab_flag
    -user_agent
    file_source
    load_timestamp
    run_datehour

int_columns:
    - ipa
    - date_field
    - time_field
    - agent_string
    - idad_index
    - idcreative_config
    - placementid
    - smartclip
    - idevent_type
    - sid,guid
    - unhex_md5_smartclip
    - options
    - file_source
    - load_timestamp
    - run_datehour

spot_columns:
    - record_type
    - date
    - time
    - spotlight_id
    - advertiser_id
    - spotlightgroup_id
    - GUID
    - queryArgs
    - browser
    - ip_address
    - privacy
    - track_id
    - user_agent
    - spotlight_request_guid
    - file_source,
    - load_timestamp
    - run_datehour

state_columns:
    - record_type
    - date
    - time
    - event
    - ipn
    - iab_flag
    - config_id
    - impression_id
    - ip_address
    - product
    - data
    - impression_guid
    - file_source
    - load_timestamp
    - run_datehour

track_columns:
    - record_type
    - date
    - time
    - event
    - spotlight_id
    - spotlightgroup_id
    - track_id
    - ip_address
    - product
    - data
    - spotlight_request_guid
    - file_source
    - load_timestamp
    - run_datehour
