schedule_interval: "30 * * * *"

path:
    - adlogs/log_process/ipn_blacklist
    - adlogs/log_process/smart_clip_patch
    - adlogs/log_process/set_interaction_smartclip_placement
adlogs/log_process/ipn_blacklist_tables:
    - imp
    - click
    - state
adlogs/log_process/smart_clip_patch_tables:
    - imp
    - click
adlogs/log_process/set_interaction_smartclip_placement_tables:
    - int

parent_directory: 'stage_{}_logs_dev'
log_path: 'log/*'


